version: "3.9"
services:
  db_backup:
    image: bash:latest
    container_name: db-backup-container
    volumes:
      - db_backups:/backups # Use a named volume for backups
      - ./backup.sh:/backup.sh # Mount the backup script
    environment:
      MYSQL_HOST: 0.0.0.0
      MYSQL_PORT: 6200
      MYSQL_USER: root
      MYSQL_PASSWORD: J6bDrh24
      MYSQL_DATABASE: ict_lms
    entrypoint: >
      /bin/sh -c "apk add --no-cache mysql-client && while true; do echo 'Trying to connect...'; 
      mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD -e 'SHOW DATABASES;' && sh /backup.sh; sleep 86400; done"

volumes:
  db_backups: # Define a named volume for storing backups
