version: "3.9"
services:
  db_backup:
    image: bash:latest # Use a lightweight Bash container
    container_name: db-backup
    volumes:
      - ./db_backups:/backups # Store backups on host
      - ./backup.sh:/backup.sh # Mount custom backup script
    environment:
      MYSQL_HOST: 95.111.248.142 # MariaDB host IP address
      MYSQL_PORT: 3306           # MariaDB port
      MYSQL_USER: root           # MariaDB username
      MYSQL_PASSWORD: J6bDrh24   # MariaDB password
      MYSQL_DATABASE: ict_lms    # Database name
    entrypoint: /bin/sh -c "apk add --no-cache mysql-client && while true; do sh ./backup.sh; sleep 5; done"
      # Run backup every hour

volumes:
  db_backups:
